version: "3"

services:
  postgres:
    build: .
    container_name: postgres-with-pg-vector
    ports:
      - "15432:5432"
    volumes:
      - postgres-with-pg-vector-vol:/var/lib/postgresql/data
      - ./init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgvector-exploration

volumes:
  postgres-with-pg-vector-vol:
